const products = [
  {
    id: 1,
    code: "YYS-001",
    name: "Benidson Aerysm Kaos Oversized T-Shirt Polos Korean Style",
    price: 79900,
    originalPrice: 200000,
    rating: 4.9,
    reviewCount: 202,
    sold: 863,
    location: "KAB. BANYUWANGI",
    image: "storage/1.webp",
    category: "Fashion",
    description:
      "Benidson Aerysm Kaos Oversized T-Shirt Polos Korean Style hadir dengan bahan Aerysm yang ringan, adem, dan super nyaman dipakai seharian, memberikan sensasi lembut di kulit serta sirkulasi udara yang baik. Desain polos minimalis dengan potongan oversized ala Korean style membuat tampilan terlihat clean, modern, dan effortlessly stylish, mudah dipadukan dengan berbagai outfit seperti jeans, cargo, atau outer favorit untuk aktivitas harian, hangout, maupun casual look.",
    shopeeLink: "https://s.shopee.co.id/8fLf47UXRo",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEA4wuk3Tq8-2Ttqs/",
  },
  {
    id: 2,
    code: "YYS-002",
    name: "Benidson Oversized Tshirt Kaos Garis-Garis Katun",
    price: 108400,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "2,3RB",
    sold: "5RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/2.webp",
    category: "Fashion",
    description:
      "Tampil santai dan stylish dengan Benidson Oversized Tshirt berbahan katun premium yang lembut, adem, dan nyaman dipakai seharian. Desain garis-garis modern memberikan kesan kasual kekinian, cocok untuk berbagai aktivitas seperti hangout, kuliah, kerja santai, hingga daily outfit.",
    shopeeLink: "https://s.shopee.co.id/gJNbCEfYt",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAVxmf2ETq-3DIdr/",
  },
  {
    id: 3,
    code: "YYS-003",
    name: "Benidson Oversized Tshirt Liquor Katun Korean",
    price: 99900,
    originalPrice: 200000,
    rating: 4.9,
    reviewCount: 801,
    sold: "2RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/3.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Tshirt Liquor Katun Korean hadir dengan desain grafis bertema liquor yang bold dan stylish, dipadukan dengan bahan katun berkualitas yang lembut, adem, dan nyaman dipakai seharian. Potongan oversized ala Korean style memberikan kesan trendy dan santai, cocok untuk daily outfit, hangout, atau streetwear look, serta mudah dipadukan dengan jeans, cargo, maupun sneakers favorit.",
    shopeeLink: "https://s.shopee.co.id/VzxPCkC9x",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAVpSHJ43s-VNm8a/",
  },
  {
    id: 4,
    code: "YYS-004",
    name: "BENIDSON Oversized Tshirt Sheesh",
    price: 99900,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "3,5RB",
    sold: "7RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/4.webp",
    category: "Fashion",
    description:
      "BENIDSON Oversized Tshirt Sheesh hadir dengan desain grafis “Sheesh” yang catchy dan penuh karakter, cocok untuk kamu yang ingin tampil standout dengan gaya kasual modern. Dibuat dari bahan katun yang adem, lembut, dan nyaman dipakai seharian, kaos ini mengusung potongan oversized yang mengikuti tren Korean street style, mudah dipadukan dengan berbagai outfit untuk aktivitas harian maupun hangout.",
    shopeeLink: "https://s.shopee.co.id/8V2EwAnyRp",
    tiktokLink: "",
  },
  {
    id: 5,
    code: "YYS-005",
    name: "Benidson Oversized Kaos Bump Katun Korean Style",
    price: 99900,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "2,6RB",
    sold: "5RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/5.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Kaos Bump Katun Korean Style hadir dengan desain grafis “Bump” yang simpel namun eye-catching, dipadukan dengan bahan katun berkualitas yang lembut, adem, dan nyaman dipakai sepanjang hari. Potongan oversized khas Korean style memberikan tampilan kasual modern yang trendy, mudah dipadukan dengan jeans, cargo, atau outfit favorit untuk daily look dan hangout.",
    shopeeLink: "https://s.shopee.co.id/3B0iaajRTw",
    tiktokLink: "",
  },
  {
    id: 6,
    code: "YYS-006",
    name: "Benidson Oversized Tshirt Stick Logo Katun M-2XL",
    price: 99900,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "2,8RB",
    sold: "5RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/6.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Tshirt Stick Logo Katun M–2XL hadir dengan desain logo stick yang minimalis dan modern, cocok untuk tampilan simpel namun tetap stylish. Terbuat dari bahan katun berkualitas yang adem, lembut, dan nyaman dipakai seharian, kaos ini menggunakan potongan oversized ala Korean style dengan pilihan ukuran M hingga 2XL, mudah dipadukan dengan berbagai outfit untuk aktivitas harian maupun hangout.",
    shopeeLink: "https://s.shopee.co.id/2LRbbIQfvV",
    tiktokLink: "",
  },
  {
    id: 7,
    code: "YYS-007",
    name: "Benidson Oversized Tshirt Katun Unisex L-2XL",
    price: 99900,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "5,2RB",
    sold: "10RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/7.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Tshirt Katun Unisex L–2XL hadir dengan desain simpel dan potongan oversized yang nyaman, cocok digunakan oleh pria maupun wanita. Terbuat dari bahan katun berkualitas yang adem, lembut, dan menyerap keringat, kaos ini nyaman dipakai seharian serta mudah dipadukan dengan berbagai gaya outfit kasual untuk aktivitas harian, hangout, maupun santai.",
    shopeeLink: "https://s.shopee.co.id/9zr2jUYf8y",
    tiktokLink: "",
  },
  {
    id: 8,
    code: "YYS-008",
    name: "Benidson Oversized Tshirt Squarepants Power Katun M-2XL",
    price: 99900,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "2,4RB",
    sold: "4RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/8.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Tshirt Squarepants Power Katun M–2XL hadir dengan desain grafis Squarepants Power yang fun dan eye-catching, cocok untuk kamu yang ingin tampil playful namun tetap stylish. Terbuat dari bahan katun berkualitas yang adem, lembut, dan nyaman dipakai seharian, kaos ini mengusung potongan oversized ala Korean style dengan pilihan ukuran M hingga 2XL, mudah dipadukan dengan berbagai outfit kasual untuk daily look maupun hangout.",
    shopeeLink: "https://s.shopee.co.id/2LRbbfOwkG",
    tiktokLink: "",
  },
  {
    id: 9,
    code: "YYS-009",
    name: "Benidson Oversized Tshirt Green Issue Katun Korean",
    price: 99900,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "1,1RB",
    sold: "2RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/9.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Tshirt Green Issue Katun Korean hadir dengan desain bertema Green Issue yang modern dan berkarakter, cocok untuk tampilan kasual yang fresh dan kekinian. Terbuat dari bahan katun berkualitas yang adem, lembut, dan nyaman dipakai seharian, kaos ini mengusung potongan oversized ala Korean style sehingga mudah dipadukan dengan berbagai outfit untuk aktivitas harian maupun hangout.",
    shopeeLink: "https://s.shopee.co.id/8zyVY6ydcr",
    tiktokLink: "",
  },
  {
    id: 10,
    code: "YYS-010",
    name: "Benidson Oversized Tshirt Jaguars Katun Korean",
    price: 99900,
    originalPrice: 200000,
    rating: 4.9,
    reviewCount: "149",
    sold: "440",
    location: "KAB. BANYUWANGI",
    image: "storage/10.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Tshirt Jaguars Katun Korean hadir dengan desain grafis Jaguars yang bold dan sporty, memberikan kesan kuat dan stylish pada tampilan kasualmu. Dibuat dari bahan katun berkualitas yang adem, lembut, dan nyaman dipakai seharian, kaos ini mengusung potongan oversized ala Korean style yang trendy dan mudah dipadukan dengan berbagai outfit untuk aktivitas harian maupun hangout.",
    shopeeLink: "https://s.shopee.co.id/1gBuop112T",
    tiktokLink: "",
  },
  {
    id: 11,
    code: "YYS-011",
    name: "Thenational Oversize T-Shirt Discredit Black Katun Premium",
    price: 88000,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "2,4RB",
    sold: "5RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/11.webp",
    category: "Fashion",
    description:
      "Thenational Oversize T-Shirt Discredit Black Katun Premium hadir dengan desain grafis “Discredit” bernuansa hitam yang tegas dan modern, cocok untuk kamu yang ingin tampil bold dan berkarakter. Terbuat dari bahan katun premium yang lembut, adem, dan nyaman dipakai seharian, kaos ini mengusung potongan oversize yang trendy serta mudah dipadukan dengan berbagai outfit streetwear maupun kasual untuk aktivitas harian.",
    shopeeLink: "https://s.shopee.co.id/3VdZgDa2sr",
    tiktokLink: "",
  },
  {
    id: 12,
    code: "YYS-012",
    name: "Thenational Boxy Fit Oversized T-Shirt Brody Katun Combed 24s",
    price: 200000,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "704",
    sold: "2RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/12.webp",
    category: "Fashion",
    description:
      "Thenational Boxy Fit Oversized T-Shirt Brody Katun Combed 24s hadir dengan potongan boxy fit yang modern dan proporsional, memberikan tampilan kasual yang clean namun tetap stylish. Terbuat dari bahan katun combed 24s berkualitas yang lembut, adem, dan nyaman dipakai seharian, kaos ini cocok untuk daily wear maupun streetwear look, serta mudah dipadukan dengan berbagai outfit favoritmu.",
    shopeeLink: "https://s.shopee.co.id/30hJ5ZA7By",
    tiktokLink: "",
  },
  {
    id: 13,
    code: "YYS-013",
    name: "Thenational Oversize T-Shirt Chase Black Katun Combed 24s",
    price: 88000,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "940",
    sold: "2RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/13.webp",
    category: "Fashion",
    description:
      "Thenational Oversize T-Shirt Chase Black Katun Combed 24s hadir dengan desain simpel berwarna hitam yang timeless dan mudah dipadukan dengan berbagai gaya. Terbuat dari bahan katun combed 24s berkualitas yang lembut, adem, dan nyaman dipakai seharian, kaos ini mengusung potongan oversize yang modern, cocok untuk tampilan kasual maupun streetwear sehari-hari.",
    shopeeLink: "https://s.shopee.co.id/4fpX4xrVPk",
    tiktokLink: "",
  },
  {
    id: 14,
    code: "YYS-014",
    name: "Thenational Oversize T-shirt Number Line Black",
    price: 94000,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "875",
    sold: "2RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/14.webp",
    category: "Fashion",
    description:
      "Thenational Oversize T-Shirt Number Line Black hadir dengan desain grafis Number Line yang minimalis dan modern, memberikan kesan clean namun tetap berkarakter pada tampilan kasualmu. Dengan warna hitam yang timeless dan potongan oversize yang nyaman, kaos ini cocok untuk dipakai sehari-hari maupun gaya streetwear, serta mudah dipadukan dengan berbagai outfit favorit.",
    shopeeLink: "https://s.shopee.co.id/3B0jIUOvb9",
    tiktokLink: "",
  },
  {
    id: 15,
    code: "YYS-015",
    name: "Thenational Oversize T-Shirt Katun Hitam S-XL",
    price: 88000,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "345",
    sold: "777",
    location: "KAB. BANYUWANGI",
    image: "storage/15.webp",
    category: "Fashion",
    description:
      "Thenational Oversize T-Shirt Katun Hitam S–XL hadir dengan desain simpel dan warna hitam yang timeless, cocok untuk berbagai gaya kasual maupun streetwear. Terbuat dari bahan katun yang lembut, adem, dan nyaman dipakai seharian, kaos ini menggunakan potongan oversize yang modern dengan pilihan ukuran S hingga XL, mudah dipadukan dengan berbagai outfit favorit untuk aktivitas harian.",
    shopeeLink: "https://s.shopee.co.id/BN7jC4qSi",
    tiktokLink: "",
  },
  {
    id: 16,
    code: "YYS-016",
    name: "Thenational Oversize Rugby Polo Shirt DarkSynergy",
    price: 98000,
    originalPrice: 220000,
    rating: 4.8,
    reviewCount: "888",
    sold: "2RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/16.webp",
    category: "Fashion",
    description:
      "Thenational Oversize Rugby Polo Shirt DarkSynergy hadir dengan desain rugby polo bernuansa DarkSynergy yang maskulin dan modern, memadukan gaya sporty dan streetwear dalam satu tampilan. Mengusung potongan oversize yang nyaman, kaos polo ini cocok untuk aktivitas harian maupun casual look, serta mudah dipadukan dengan berbagai outfit untuk tampil standout namun tetap santai.",
    shopeeLink: "https://s.shopee.co.id/2g4ShwZYIf",
    tiktokLink: "",
  },
  {
    id: 17,
    code: "YYS-017",
    name: "Thenational Oversize T-Shirt Katun Combed 24s Hitam",
    price: 88000,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "691",
    sold: "1RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/17.webp",
    category: "Fashion",
    description:
      "Thenational Oversize T-Shirt Katun Combed 24s Hitam hadir dengan desain simpel dan warna hitam yang timeless, memberikan tampilan kasual yang clean dan mudah dipadukan. Terbuat dari bahan katun combed 24s berkualitas yang lembut, adem, dan nyaman dipakai seharian, kaos ini menggunakan potongan oversize modern yang cocok untuk daily wear maupun gaya streetwear.",
    shopeeLink: "https://s.shopee.co.id/20oluyeDhb",
    tiktokLink: "",
  },
  {
    id: 18,
    code: "YYS-018",
    name: "Thenational Boxy Fit 24s Oversized T-shirt Scott",
    price: 86000,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "139",
    sold: "428",
    location: "KAB. BANYUWANGI",
    image: "storage/18.webp",
    category: "Fashion",
    description:
      "Thenational Boxy Fit 24s Oversized T-Shirt Scott hadir dengan potongan boxy fit yang modern dan proporsional, memberikan siluet kasual yang rapi namun tetap trendy. Terbuat dari bahan katun 24s berkualitas yang lembut, adem, dan nyaman dipakai seharian, kaos ini cocok untuk daily wear maupun streetwear look, serta mudah dipadukan dengan berbagai outfit favorit.",
    shopeeLink: "https://s.shopee.co.id/2qNsuh6DLs",
    tiktokLink: "",
  },
  {
    id: 19,
    code: "YYS-019",
    name: "Thenational Oversize T-shirt Dressing Dark Purple",
    price: 88000,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "1RB",
    sold: "2RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/19.webp",
    category: "Fashion",
    description:
      "Thenational Oversize T-Shirt Dressing Dark Purple hadir dengan desain modern bernuansa dark purple yang elegan dan berkarakter, cocok untuk kamu yang ingin tampil beda namun tetap stylish. Mengusung potongan oversize yang nyaman, kaos ini pas untuk daily wear maupun streetwear look, serta mudah dipadukan dengan berbagai outfit kasual favorit.",
    shopeeLink: "https://s.shopee.co.id/3VdZi3giuX",
    tiktokLink: "",
  },
  {
    id: 20,
    code: "YYS-020",
    name: "Thenational Oversized T-shirt Smile White Kaos Pria & Wanita",
    price: 200000,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "719",
    sold: "1RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/20.webp",
    category: "Fashion",
    description:
      "Thenational Oversized T-Shirt Smile White Kaos Pria & Wanita hadir dengan desain grafis “Smile” yang playful dan fresh, memberikan kesan ceria pada tampilan kasual. Dengan warna putih yang clean dan potongan oversized yang nyaman, kaos ini cocok dipakai oleh pria maupun wanita, mudah dipadukan dengan berbagai outfit untuk daily wear, hangout, maupun gaya streetwear santai.",
    shopeeLink: "https://s.shopee.co.id/50SNUyX2gP",
    tiktokLink: "",
  },
  {
    id: 21,
    code: "YYS-021",
    name: "AF - Jasmine Vest Bordir Rompi Pakaian Wanita Outer Korean Style",
    price: 75400,
    originalPrice: 75400,
    rating: 4.9,
    reviewCount: 469,
    sold: "1RB+",
    location: "KAB. BANDUNG",
    image: "storage/21.webp",
    category: "Fashion",
    description:
      "AF – Jasmine Vest Bordir Rompi Pakaian Wanita Outer Korean Style hadir dengan desain rompi bordir yang anggun dan feminin, memberikan sentuhan elegan pada setiap tampilan. Cocok digunakan sebagai outer ala Korean style, vest ini mudah dipadukan dengan kemeja, blouse, atau dress favorit untuk menciptakan look kasual hingga semi-formal yang stylish dan modern.",
    shopeeLink: "https://s.shopee.co.id/9KbOEfCJb6",
    tiktokLink: "",
  },
  {
    id: 22,
    code: "YYS-022",
    name: "EVI VEST / VEST BASIC WANITA / Vest Semiwol Atasan Wanita Crop EVI Vest Casual VEST TERLARIS",
    price: 46900,
    originalPrice: 97500,
    rating: 4.9,
    reviewCount: "6RB",
    sold: "10RB+",
    location: "KAB. PEKALONGAN",
    image: "storage/22.webp",
    category: "Fashion",
    description:
      "EVI Vest / Vest Basic Wanita hadir dengan desain crop yang simpel dan modern, terbuat dari bahan semiwol yang nyaman dan memberikan kesan rapi saat dikenakan. Cocok digunakan sebagai atasan maupun outer casual, vest terlaris ini mudah dipadukan dengan kemeja, kaos, atau dress untuk menciptakan tampilan wanita yang stylish, santai, dan kekinian.",
    shopeeLink: "https://s.shopee.co.id/7KqJr7CR1f",
    tiktokLink: "",
  },
  {
    id: 23,
    code: "YYS-023",
    name: "Naomi Vest Set - Set Blazer Wanita - Vest Outer Set - Setelan Rok Wanita",
    price: 133105,
    originalPrice: 285000,
    rating: 4.9,
    reviewCount: "10RB",
    sold: "10RB+",
    location: "KAB. PEKALONGAN",
    image: "storage/23.webp",
    category: "Fashion",
    description:
      "Naomi Vest Set – Set Blazer Wanita hadir sebagai setelan vest outer dengan rok yang memberikan tampilan feminin, rapi, dan elegan dalam satu paket. Cocok untuk berbagai kesempatan mulai dari kerja, acara formal, hingga semi-formal, set ini mudah dipadukan dengan inner favorit untuk menciptakan gaya wanita yang modern, stylish, dan berkelas.",
    shopeeLink: "https://s.shopee.co.id/7pmaSJoLIn",
    tiktokLink: "",
  },
  {
    id: 24,
    code: "YYS-024",
    name: "Namala Blouse Atasan Wanita Lengan Panjang Kemeja Jeans Crop Top dengan Desain Stylish dan Nyaman untuk Tampil Harian",
    price: 97950,
    originalPrice: 150500,
    rating: 4.9,
    reviewCount: "983",
    sold: "5RB+",
    location: "KAB. PEKALONGAN",
    image: "storage/24.webp",
    category: "Fashion",
    description:
      "Namala Blouse Atasan Wanita Lengan Panjang hadir dengan desain kemeja jeans crop top yang stylish dan modern, memberikan tampilan kasual yang fresh dan kekinian. Nyaman dipakai untuk aktivitas harian, blouse ini mudah dipadukan dengan berbagai bawahan seperti jeans, rok, atau celana high waist untuk menciptakan gaya wanita yang modis, simpel, dan tetap nyaman sepanjang hari.",
    shopeeLink: "https://s.shopee.co.id/4AtI6AsvKL",
    tiktokLink: "",
  },
  {
    id: 25,
    code: "YYS-025",
    name: "FLIDA FASIHON - 020 Cardigan rajut wanita PREMIUM BEST SELLER kancing hidup kerah Uneck lengan panjang",
    price: 176000,
    originalPrice: 400000,
    rating: 4.9,
    reviewCount: "2,9RB",
    sold: "7RB+",
    location: "KOTA JAKARTA BARAT",
    image: "storage/25.webp",
    category: "Fashion",
    description:
      "FLIDA FASHION – 020 Cardigan Rajut Wanita Premium Best Seller hadir dengan bahan rajut premium yang lembut, hangat, dan nyaman dipakai, dilengkapi kancing hidup, kerah U-neck, serta lengan panjang untuk tampilan rapi dan elegan. Desainnya simpel namun classy, mudah dipadukan sebagai outer maupun atasan, cocok untuk berbagai aktivitas harian hingga acara santai dengan gaya wanita yang stylish dan timeless.",
    shopeeLink: "https://s.shopee.co.id/8V2HGUFAkJ",
    tiktokLink: "",
  },
  {
    id: 26,
    code: "YYS-026",
    name: "Arika Blouse Stripe Atasan Peplum Wanita Salur Lengan Puff Fit Body Fitted - Blouse Atasan Wanita",
    price: 40500,
    originalPrice: 155000,
    rating: 4.8,
    reviewCount: "6,5RB",
    sold: "10RB+",
    location: "KAB. PEKALONGAN",
    image: "storage/26.webp",
    category: "Fashion",
    description:
      "Arika Blouse Stripe Atasan Peplum Wanita hadir dengan motif salur yang elegan, dipadukan desain peplum dan lengan puff yang memberikan siluet feminin serta fit body fitted yang menonjolkan bentuk tubuh dengan anggun. Cocok untuk berbagai aktivitas, blouse ini mudah dipadukan dengan rok maupun celana untuk tampilan wanita yang stylish, rapi, dan tetap nyaman dipakai seharian.",
    shopeeLink: "https://s.shopee.co.id/10wGL5Tldz",
    tiktokLink: "",
  },
  {
    id: 27,
    code: "YYS-027",
    name: "Queenie Outer By Boonaachic | Atasan Wanita | Baju Wanita | Baju Atasan Wanita Terbaru",
    price: 99999,
    originalPrice: 119000,
    rating: 4.9,
    reviewCount: "7,2RB",
    sold: "10RB+",
    location: "KOTA TASIKMALAYA",
    image: "storage/27.webp",
    category: "Fashion",
    description:
      "Queenie Outer by Boonaachic hadir sebagai atasan wanita dengan desain modern dan elegan, cocok untuk melengkapi berbagai gaya busana wanita masa kini. Mudah dipadukan dengan inner favorit, outer ini memberikan tampilan rapi namun tetap stylish, pas digunakan untuk aktivitas harian, hangout, maupun acara semi-formal dengan sentuhan fashion terbaru.",
    shopeeLink: "https://s.shopee.co.id/AKTvSWIAQI",
    tiktokLink: "",
  },
  {
    id: 28,
    code: "YYS-028",
    name: "Kaos Baseball Wanita Oversize Katun Premium Design Angka Terbaru RR Fashion ID",
    price: 69700,
    originalPrice: 129000,
    rating: 4.9,
    reviewCount: "1,4RB",
    sold: "5RB+",
    location: "KAB. BANDUNG",
    image: "storage/28.webp",
    category: "Fashion",
    description:
      "Kaos Baseball Wanita Oversize Katun Premium Design Angka Terbaru RR Fashion ID hadir dengan desain angka modern bergaya baseball yang sporty dan kekinian, memberikan tampilan kasual yang standout. Terbuat dari katun premium yang lembut, adem, dan nyaman dipakai seharian, kaos oversize ini cocok untuk berbagai aktivitas harian maupun streetwear look, serta mudah dipadukan dengan jeans, rok, atau celana favoritmu.",
    shopeeLink: "https://s.shopee.co.id/gJPx6Pf9z",
    tiktokLink: "",
  },
  {
    id: 29,
    code: "YYS-029",
    name: "Vana Blouse - Atasan Pelpum Fit Body Knit - Blouse Lengan Panjang Wanita - Atasan Wanita",
    price: 51000,
    originalPrice: 150000,
    rating: 4.9,
    reviewCount: "1,4RB",
    sold: "5RB+",
    location: "KAB. BANDUNG",
    image: "storage/29.webp",
    category: "Fashion",
    description:
      "Vana Blouse – Atasan Peplum Fit Body Knit hadir dengan desain feminin yang menawan, memadukan siluet peplum dan potongan fit body yang menonjolkan bentuk tubuh dengan elegan. Terbuat dari bahan knit yang nyaman, blouse lengan panjang ini cocok untuk berbagai aktivitas, mudah dipadukan dengan rok maupun celana untuk tampilan wanita yang rapi, stylish, dan modern.",
    shopeeLink: "https://s.shopee.co.id/8060h7b8xI",
    tiktokLink: "",
  },
  {
    id: 30,
    code: "YYS-030",
    name: "VELMO Yuki Shirt Katun - ATASAN WANITA - KEMEJA WANITA OVERSIZE",
    price: 79000,
    originalPrice: 95000,
    rating: 4.8,
    reviewCount: "7,1RB",
    sold: "10RB+",
    location: "KOTA TANGERANG SELATAN",
    image: "storage/30.webp",
    category: "Fashion",
    description:
      "VELMO Yuki Shirt Katun – Atasan Wanita Kemeja Oversize hadir dengan desain kemeja oversize yang simpel dan modern, memberikan tampilan santai namun tetap rapi. Terbuat dari bahan katun yang adem, lembut, dan nyaman dipakai seharian, kemeja ini mudah dipadukan dengan berbagai bawahan untuk menciptakan gaya wanita yang kasual, stylish, dan kekinian.",
    shopeeLink: "https://s.shopee.co.id/10wGMUmrdQ",
    tiktokLink: "",
  },
  {
    id: 31,
    code: "YYS-031",
    name: "JINISO - Ultra Highwaist Cutbray Stretch Jeans Hangout",
    price: 199000,
    originalPrice: 598571,
    rating: 4.9,
    reviewCount: "44,1RB",
    sold: "10RB+",
    location: "KOTA JAKARTA UTARA",
    image: "storage/31.webp",
    category: "Fashion",
    description:
      "JINISO – Ultra Highwaist Cutbray Stretch Jeans Hangout hadir dengan potongan highwaist yang menonjolkan siluet kaki lebih jenjang, dipadukan model cutbray yang stylish dan kekinian. Terbuat dari bahan jeans stretch yang nyaman dan fleksibel, celana ini cocok untuk hangout maupun aktivitas harian, mudah dipadukan dengan berbagai atasan untuk tampilan kasual yang trendi dan percaya diri.",
    shopeeLink: "https://s.shopee.co.id/AUnQQx2xmL",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAbuJnjtyG-P5IUM/",
  },
  {
    id: 32,
    code: "YYS-032",
    name: "JINISO - Ultra Highwaist Baggy Loose Overtime Jeans",
    price: 231500,
    originalPrice: 655714,
    rating: 4.9,
    reviewCount: "28,2RB",
    sold: "10RB+",
    location: "KOTA JAKARTA UTARA",
    image: "storage/32.webp",
    category: "Fashion",
    description:
      "JINISO – Ultra Highwaist Baggy Loose Overtime Jeans hadir dengan potongan highwaist yang memberikan kesan kaki lebih jenjang, dipadukan model baggy loose yang santai dan kekinian. Terbuat dari bahan jeans yang nyaman dipakai seharian, celana ini cocok untuk aktivitas harian maupun hangout, mudah dipadukan dengan berbagai atasan untuk tampilan kasual yang stylish dan modern.",
    shopeeLink: "https://s.shopee.co.id/20osJWljKK",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAqvV2xqXH-BaK9b/",
  },
  {
    id: 33,
    code: "YYS-033",
    name: "JINISO - Highwaist Stretch Cutbray Pocket Jeans Hangout",
    price: 208000,
    originalPrice: 598571,
    rating: 4.9,
    reviewCount: "23,7RB",
    sold: "10RB+",
    location: "KOTA JAKARTA UTARA",
    image: "storage/33.webp",
    category: "Fashion",
    description:
      "JINISO – Highwaist Stretch Cutbray Pocket Jeans Hangout hadir dengan desain highwaist yang menonjolkan siluet tubuh, dipadukan model cutbray dengan detail pocket yang stylish. Terbuat dari bahan jeans stretch yang elastis dan nyaman dipakai seharian, celana ini cocok untuk hangout maupun aktivitas harian, mudah dipadukan dengan berbagai atasan untuk tampilan kasual yang trendi dan percaya diri.",
    shopeeLink: "https://s.shopee.co.id/5Alu5PY7yk",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAbcn1tLqC-dAPWh/",
  },
  {
    id: 34,
    code: "YYS-034",
    name: "JINISO - Highwaist Oversize Baggy Loose Jeans 688 WEEKEND",
    price: 231500,
    originalPrice: 655714,
    rating: 4.9,
    reviewCount: "2RB",
    sold: "4RB+",
    location: "KOTA JAKARTA UTARA",
    image: "storage/34.webp",
    category: "Fashion",
    description:
      "JINISO – Highwaist Oversize Baggy Loose Jeans 688 WEEKEND hadir dengan potongan highwaist yang memberi kesan kaki lebih jenjang, dipadukan model oversize baggy loose yang santai dan kekinian. Terbuat dari bahan jeans berkualitas yang nyaman dipakai seharian, celana ini cocok untuk weekend look maupun aktivitas kasual, mudah dipadukan dengan berbagai atasan untuk tampilan stylish dan effortless.",
    shopeeLink: "https://s.shopee.co.id/9UutFZ8eu2",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAgkb8fq1m-aZ6Rn/",
  },
  {
    id: 35,
    code: "YYS-035",
    name: "JINISO - Jorts Baggy Short Jeans Skater",
    price: 176000,
    originalPrice: 570000,
    rating: 4.9,
    reviewCount: "2,2RB",
    sold: "6RB+",
    location: "KOTA JAKARTA UTARA",
    image: "storage/35.webp",
    category: "Fashion",
    description:
      "JINISO – Jorts Baggy Short Jeans Skater hadir dengan model jorts baggy yang longgar dan nyaman, mengusung gaya skater yang santai dan kekinian. Terbuat dari bahan jeans berkualitas yang kuat namun tetap nyaman dipakai, celana pendek ini cocok untuk aktivitas harian maupun hangout, mudah dipadukan dengan kaos atau hoodie favorit untuk tampilan kasual yang stylish.",
    shopeeLink: "https://s.shopee.co.id/qcuvpsKpg",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAguR6jxSo-XgKxo/",
  },
  {
    id: 36,
    code: "YYS-036",
    name: "JINISO - Highwaist Rok Ashley Jeans Panjang 908 SEVENTY",
    price: 228999,
    originalPrice: 655714,
    rating: 4.9,
    reviewCount: "5,2RB",
    sold: "10RB+",
    location: "KOTA JAKARTA UTARA",
    image: "storage/36.webp",
    category: "Fashion",
    description:
      "JINISO – Highwaist Rok Ashley Jeans Panjang 908 SEVENTY hadir dengan desain highwaist yang memberi kesan kaki lebih jenjang, dipadukan potongan rok jeans panjang yang simpel dan elegan. Terbuat dari bahan denim berkualitas yang nyaman dipakai, rok ini cocok untuk aktivitas harian maupun hangout, mudah dipadukan dengan berbagai atasan untuk tampilan kasual yang modern dan stylish.",
    shopeeLink: "https://s.shopee.co.id/1gC1vc4pKk",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEApDwFDEnf-8RPwF/",
  },
  {
    id: 37,
    code: "YYS-037",
    name: "JINISO - Oversize Jaket Jeans",
    price: 210500,
    originalPrice: 598571,
    rating: 4.9,
    reviewCount: "10,2RB",
    sold: "10RB+",
    location: "KOTA JAKARTA UTARA",
    image: "storage/37.webp",
    category: "Fashion",
    description:
      "JINISO – Oversize Jaket Jeans hadir dengan desain jaket denim oversize yang trendy dan kekinian, memberikan tampilan kasual yang stylish dan effortless. Terbuat dari bahan jeans berkualitas yang nyaman dipakai, jaket ini cocok dijadikan outer untuk berbagai aktivitas, mudah dipadukan dengan kaos, hoodie, atau dress untuk menciptakan look modern dan fashionable.",
    shopeeLink: "https://s.shopee.co.id/5L5KIdwnR6",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEApbuMDnbV-1i5mA/",
  },
  {
    id: 38,
    code: "YYS-038",
    name: "JINISO Jaket Crop Jeans Oversize Boxy Bio Spray",
    price: 210500,
    originalPrice: 598571,
    rating: 4.9,
    reviewCount: "543",
    sold: "1RB+",
    location: "KOTA JAKARTA UTARA",
    image: "storage/38.webp",
    category: "Fashion",
    description:
      "JINISO Jaket Crop Jeans Oversize Boxy Bio Spray hadir dengan desain crop dan potongan oversize boxy yang modern, memberikan tampilan edgy dan kekinian. Terbuat dari bahan denim berkualitas dengan sentuhan bio spray, jaket ini nyaman dipakai sebagai outer untuk berbagai aktivitas, mudah dipadukan dengan berbagai outfit untuk menciptakan gaya kasual yang stylish dan standout.",
    shopeeLink: "https://s.shopee.co.id/1gC5FFkdV7",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAsDejacEk-caOQo/",
  },
  {
    id: 39,
    code: "YYS-039",
    name: "JINISO - Ultra Highwaist Baggy Loose Jeans 665 OVERTIME",
    price: 231500,
    originalPrice: 655714,
    rating: 4.9,
    reviewCount: "1,5RB",
    sold: "3RB+",
    location: "KOTA JAKARTA UTARA",
    image: "storage/39.webp",
    category: "Fashion",
    description:
      "JINISO – Ultra Highwaist Baggy Loose Jeans 665 OVERTIME hadir dengan potongan ultra highwaist yang memberikan siluet kaki lebih jenjang, dipadukan model baggy loose yang santai dan kekinian. Terbuat dari bahan jeans berkualitas yang nyaman dipakai seharian, celana ini cocok untuk aktivitas harian maupun hangout, mudah dipadukan dengan berbagai atasan untuk tampilan kasual yang stylish dan modern.",
    shopeeLink: "https://s.shopee.co.id/4q93iO7dtB",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAsGxRCSDL-0Hgpj/",
  },
  {
    id: 40,
    code: "YYS-040",
    name: "JINISO - Highwaist Oversize Baggy Loose Jeans 773 WEEKEND",
    price: 231500,
    originalPrice: 655714,
    rating: 4.9,
    reviewCount: "5,8RB",
    sold: "10RB+",
    location: "KOTA JAKARTA UTARA",
    image: "storage/40.webp",
    category: "Fashion",
    description:
      "JINISO – Highwaist Oversize Baggy Loose Jeans 773 WEEKEND hadir dengan potongan highwaist yang memberikan kesan kaki lebih jenjang, dipadukan model oversize baggy loose yang santai dan kekinian. Terbuat dari bahan jeans berkualitas yang nyaman dipakai seharian, celana ini cocok untuk weekend look maupun aktivitas kasual, mudah dipadukan dengan berbagai atasan untuk tampilan modern, stylish, dan effortless.",
    shopeeLink: "https://s.shopee.co.id/9AI2saLNLt",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAgdt86gU5-bnI2F/",
  },
  {
    id: 41,
    code: "YYS-041",
    name: "LADY COLLECTION - P0L0 Kardigan Rajut Bordir Lengan Panjang Wanita O Neck kancing hidup 020",
    price: 176000,
    originalPrice: 400000,
    rating: 4.9,
    reviewCount: "20,4RB",
    sold: "10RB+",
    location: "KOTA JAKARTA BARAT",
    image: "storage/41.webp",
    category: "Fashion",
    description:
      "LADY COLLECTION – P0L0 Kardigan Rajut Bordir Lengan Panjang Wanita O-Neck 020 hadir dengan desain rajut elegan yang dilengkapi detail bordir cantik, memberikan kesan feminin dan rapi. Mengusung kerah O-neck serta kancing hidup, kardigan ini nyaman dipakai sebagai outer maupun atasan, mudah dipadukan dengan berbagai outfit untuk tampilan wanita yang stylish, hangat, dan modern.",
    shopeeLink: "https://s.shopee.co.id/6VHJm4HvoM",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAtNF1Vawo-c72VM/",
  },
  {
    id: 42,
    code: "YYS-042",
    name: "LADY COLLECTION - Polo Kaos Wanita Polos Kerah O Neck Rajut Singkat Pakaian Atasan Kemeja Knit yang Langsing B03",
    price: 129000,
    originalPrice: 400000,
    rating: 4.9,
    reviewCount: "934",
    sold: "2RB+",
    location: "KOTA JAKARTA BARAT",
    image: "storage/42.webp",
    category: "Fashion",
    description:
      "LADY COLLECTION – Polo Kaos Wanita Polos Rajut B03 hadir dengan desain kerah O-neck yang simpel dan elegan, memberikan tampilan rapi namun tetap feminin. Terbuat dari bahan knit rajut yang nyaman dan mengikuti bentuk tubuh, atasan ini cocok dipakai untuk aktivitas harian maupun acara santai, mudah dipadukan dengan rok atau celana untuk menciptakan gaya wanita yang langsing, modern, dan stylish.",
    shopeeLink: "https://s.shopee.co.id/2qO1PYdQyf",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAtD9jKbkE-vmlWJ/",
  },
  {
    id: 43,
    code: "YYS-043",
    name: "LADY COLLECTION - POLO Cardigan Wanita Kardigan rajutan lengan panjang wanita bordir wanitajaket rajutan -020",
    price: 176000,
    originalPrice: 400000,
    rating: 4.9,
    reviewCount: "2,7RB",
    sold: "6RB+",
    location: "KOTA JAKARTA BARAT",
    image: "storage/43.webp",
    category: "Fashion",
    description:
      "LADY COLLECTION – POLO Cardigan Wanita Rajutan Lengan Panjang Bordir 020 hadir dengan desain rajutan yang elegan dan detail bordir feminin, memberikan tampilan rapi namun tetap stylish. Dengan lengan panjang dan potongan yang nyaman, kardigan ini cocok digunakan sebagai outer maupun atasan, mudah dipadukan dengan berbagai outfit untuk aktivitas harian hingga acara santai dengan gaya wanita yang anggun dan modern.",
    shopeeLink: "https://s.shopee.co.id/7fTHAUPwMk",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAtKNkqMnf-J1eij/",
  },
  {
    id: 44,
    code: "YYS-044",
    name: "LADY COLLECTION - POLO Cardigan Rajut Lengan Panjang Wanita-C01",
    price: 188000,
    originalPrice: 400000,
    rating: 4.9,
    reviewCount: "474",
    sold: "1RB+",
    location: "KOTA JAKARTA BARAT",
    image: "storage/44.webp",
    category: "Fashion",
    description:
      "LADY COLLECTION – POLO Cardigan Rajut Lengan Panjang Wanita C01 hadir dengan desain rajut yang simpel dan elegan, memberikan tampilan rapi serta feminin. Mengusung potongan nyaman dengan lengan panjang, kardigan ini cocok digunakan sebagai outer maupun atasan, mudah dipadukan dengan berbagai outfit untuk aktivitas harian hingga acara santai dengan gaya wanita yang modern dan stylish.",
    shopeeLink: "https://s.shopee.co.id/1LZDd6X4Nf",
    tiktokLink: "",
  },
  {
    id: 45,
    code: "YYS-045",
    name: "LADY COLLECTION - jaket rajut wanita resleting double turtle neck lengan panjang bahan premium D16",
    price: 188000,
    originalPrice: 399000,
    rating: 4.9,
    reviewCount: "127",
    sold: "326",
    location: "KOTA JAKARTA BARAT",
    image: "storage/45.webp",
    category: "Fashion",
    description:
      "LADY COLLECTION – Jaket Rajut Wanita Resleting Double Turtle Neck D16 hadir dengan desain elegan dan fungsional, dilengkapi resleting double serta model turtle neck yang memberikan kesan hangat dan stylish. Terbuat dari bahan rajut premium yang lembut dan nyaman dipakai, jaket lengan panjang ini cocok digunakan sebagai outer untuk aktivitas harian maupun acara santai, mudah dipadukan dengan berbagai outfit untuk tampilan wanita yang modern dan berkelas.",
    shopeeLink: "https://s.shopee.co.id/5q1cznJBXv",
    tiktokLink: "",
  },
  {
    id: 46,
    code: "YYS-046",
    name: "CallieTamami - Himawari Tops Katun Poplin Bigsize",
    price: 155000,
    originalPrice: 155000,
    rating: 4.9,
    reviewCount: "2,5RB",
    sold: "5RB+",
    location: "KOTA BANDUNG",
    image: "storage/46.webp",
    category: "Fashion",
    description:
      "CallieTamami – Himawari Tops Katun Poplin Bigsize hadir dengan desain manis dan feminin, terbuat dari bahan katun poplin yang adem, ringan, dan nyaman dipakai seharian. Dirancang dengan potongan big size yang longgar dan nyaman, atasan ini cocok untuk tampilan harian yang santai namun tetap stylish, mudah dipadukan dengan berbagai bawahan untuk gaya wanita yang fresh dan percaya diri.",
    shopeeLink: "https://s.shopee.co.id/60L3CRVaKX",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAW3t4FsKF-26SPz/",
  },
  {
    id: 47,
    code: "YYS-047",
    name: "NEW YORK SET - Setelan One Set Wanita Atasan Celana Kulot Salur Stripe Formal Look Classy Elegan Fitted Body",
    price: 219900,
    originalPrice: 350000,
    rating: 5,
    reviewCount: "495",
    sold: "1RB+",
    location: "KOTA JAKARTA BARAT",
    image: "storage/47.webp",
    category: "Fashion",
    description:
      "NEW YORK SET – Setelan One Set Wanita Atasan & Celana Kulot Salur Stripe hadir dengan desain stripe yang classy dan elegan, memberikan tampilan formal look yang rapi dan berkelas. Dengan potongan fitted body yang menonjolkan siluet tubuh, setelan ini cocok digunakan untuk acara formal, kerja, maupun semi-formal, serta mudah dipadukan dengan aksesoris favorit untuk tampilan wanita yang modern dan profesional.",
    shopeeLink: "https://s.shopee.co.id/6fajztcAjT",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEAWby5vjxp-87mCz/",
  },
  {
    id: 48,
    code: "YYS-048",
    name: "Kaos Polo Wanita Arle Knitted Top HULM Basic Minimalis",
    price: 79000,
    originalPrice: 79000,
    rating: 4.9,
    reviewCount: "1,2RB",
    sold: "4RB+",
    location: "KOTA JAKARTA BARAT",
    image: "storage/48.webp",
    category: "Fashion",
    description:
      "Kaos Polo Wanita Arle Knitted Top HULM Basic Minimalis hadir dengan desain polo knit yang simpel dan elegan, menampilkan gaya minimalis yang rapi namun tetap feminin. Terbuat dari bahan rajut yang nyaman dan lembut di kulit, atasan ini cocok untuk aktivitas harian hingga tampilan smart casual, mudah dipadukan dengan rok maupun celana untuk look wanita yang modern dan stylish.",
    shopeeLink: "https://s.shopee.co.id/60L3CwTNHI",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEA7NHL6FDm-3VuDq/",
  },
  {
    id: 49,
    code: "YYS-049",
    name: "MISAE - Karla Top / Atasan Wanita Semiwoll Premium / Blouse Korean Style",
    price: 77500,
    originalPrice: 175000,
    rating: 4.9,
    reviewCount: "5RB",
    sold: "10RB+",
    location: "KOTA PEKALONGAN",
    image: "storage/49.webp",
    category: "Fashion",
    description:
      "MISAE – Karla Top / Atasan Wanita Semiwool Premium hadir dengan desain blouse ala Korean style yang elegan dan feminin, memberikan tampilan rapi namun tetap modern. Terbuat dari bahan semiwool premium yang lembut dan nyaman dipakai, atasan ini cocok untuk aktivitas harian maupun acara semi-formal, mudah dipadukan dengan berbagai bawahan untuk menciptakan gaya wanita yang stylish dan berkelas.",
    shopeeLink: "https://s.shopee.co.id/4AtP1jeuKb",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEA7kx6B9A6-sfxxy/",
  },
  {
    id: 50,
    code: "YYS-050",
    name: "IRIS TOP | Atasan Knit Wanita Korean Top Baju Knit Wanita Lengan Panjang Basic Long Sleeve",
    price: 67750,
    originalPrice: 150000,
    rating: 4.9,
    reviewCount: "3,1RB",
    sold: "10RB+",
    location: "KOTA JAKARTA UTARA",
    image: "storage/50.webp",
    category: "Fashion",
    description:
      "IRIS TOP | Atasan Knit Wanita Korean Top hadir dengan desain basic yang simpel dan elegan, dilengkapi lengan panjang (long sleeve) untuk tampilan rapi dan feminin. Terbuat dari bahan knit yang lembut, elastis, dan nyaman dipakai seharian, atasan ini cocok untuk gaya Korean look yang minimalis, mudah dipadukan dengan rok atau celana untuk aktivitas harian hingga smart casual.",
    shopeeLink: "https://s.shopee.co.id/60L3DFltKt",
    tiktokLink: "https://vt.tokopedia.com/t/ZSHEA7U5a8Sx4-9DRBR/",
  },
  // {
  //   id: 51,
  //   code: "YYS-051",
  //   name: "JINISO - Baggy Loose Jeans Urban Style",
  //   price: 229000,
  //   originalPrice: 645000,
  //   rating: 4.9,
  //   reviewCount: "4,1RB",
  //   sold: "8RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/51.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Baggy Loose Jeans Urban Style hadir dengan potongan baggy loose yang nyaman dan kekinian. Terbuat dari bahan denim berkualitas tinggi, celana ini cocok untuk aktivitas harian maupun streetwear look, mudah dipadukan dengan kaos oversized atau hoodie favorit.",
  //   shopeeLink: "https://s.shopee.co.id/dummy51",
  // tiktokLink: "",
  // },
  // {
  //   id: 52,
  //   code: "YYS-052",
  //   name: "JINISO - Highwaist Straight Jeans Clean Look",
  //   price: 224000,
  //   originalPrice: 630000,
  //   rating: 4.9,
  //   reviewCount: "3,6RB",
  //   sold: "6RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/52.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Highwaist Straight Jeans Clean Look hadir dengan potongan highwaist dan siluet lurus yang memberikan kesan rapi dan modern. Dibuat dari denim berkualitas yang nyaman dipakai seharian, cocok untuk gaya kasual maupun semi-formal.",
  //   shopeeLink: "https://s.shopee.co.id/dummy52",
  // tiktokLink: "",
  // },
  // {
  //   id: 53,
  //   code: "YYS-053",
  //   name: "JINISO - Cargo Denim Pants Oversize",
  //   price: 249000,
  //   originalPrice: 699000,
  //   rating: 4.9,
  //   reviewCount: "5,4RB",
  //   sold: "11RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/53.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Cargo Denim Pants Oversize mengusung desain cargo dengan kantong fungsional dan potongan oversize yang trendy. Terbuat dari denim tebal berkualitas, celana ini cocok untuk gaya streetwear aktif dan stylish.",
  //   shopeeLink: "https://s.shopee.co.id/dummy53",
  // tiktokLink: "",
  // },
  // {
  //   id: 54,
  //   code: "YYS-054",
  //   name: "JINISO - Rok Jeans Panjang A-Line",
  //   price: 215000,
  //   originalPrice: 599000,
  //   rating: 4.8,
  //   reviewCount: "2,1RB",
  //   sold: "4RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/54.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Rok Jeans Panjang A-Line hadir dengan potongan A-line yang memberikan kesan feminin dan elegan. Terbuat dari bahan denim nyaman, rok ini cocok untuk aktivitas harian dan mudah dipadukan dengan berbagai atasan.",
  //   shopeeLink: "https://s.shopee.co.id/dummy54",
  // tiktokLink: "",
  // },
  // {
  //   id: 55,
  //   code: "YYS-055",
  //   name: "JINISO - Jaket Jeans Oversize Boxy",
  //   price: 219000,
  //   originalPrice: 610000,
  //   rating: 4.9,
  //   reviewCount: "6,8RB",
  //   sold: "13RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/55.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Jaket Jeans Oversize Boxy hadir dengan potongan boxy oversize yang modern dan stylish. Cocok dijadikan outer untuk berbagai aktivitas kasual, memberikan tampilan trendi dan effortless.",
  //   shopeeLink: "https://s.shopee.co.id/dummy55",
  // tiktokLink: "",
  // },
  // {
  //   id: 56,
  //   code: "YYS-056",
  //   name: "JINISO - Mom Jeans Casual Fit",
  //   price: 225000,
  //   originalPrice: 625000,
  //   rating: 4.9,
  //   reviewCount: "3,4RB",
  //   sold: "7RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/56.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Mom Jeans Casual Fit hadir dengan potongan mom jeans yang nyaman dan trendi. Terbuat dari denim berkualitas yang ringan dan awet, celana ini cocok untuk gaya kasual sehari-hari.",
  //   shopeeLink: "https://s.shopee.co.id/dummy56",
  // tiktokLink: "",
  // },
  // {
  //   id: 57,
  //   code: "YYS-057",
  //   name: "JINISO - Flare Jeans Highwaist Modern",
  //   price: 239000,
  //   originalPrice: 670000,
  //   rating: 4.8,
  //   reviewCount: "1,8RB",
  //   sold: "3RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/57.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Flare Jeans Highwaist Modern menghadirkan potongan flare yang elegan dan stylish. Terbuat dari denim berkualitas yang nyaman dipakai, cocok untuk tampilan kasual maupun semi-formal.",
  //   shopeeLink: "https://s.shopee.co.id/dummy57",
  // tiktokLink: "",
  // },
  // {
  //   id: 58,
  //   code: "YYS-058",
  //   name: "JINISO - Wide Leg Jeans Daily Casual",
  //   price: 229000,
  //   originalPrice: 645000,
  //   rating: 4.9,
  //   reviewCount: "4,9RB",
  //   sold: "9RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/58.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Wide Leg Jeans Daily Casual hadir dengan potongan kaki lebar yang nyaman dan modern. Cocok untuk aktivitas harian, jeans ini mudah dipadukan dengan berbagai atasan favorit.",
  //   shopeeLink: "https://s.shopee.co.id/dummy58",
  // tiktokLink: "",
  // },
  // {
  //   id: 59,
  //   code: "YYS-059",
  //   name: "JINISO - Denim Short Pants Relaxed Fit",
  //   price: 169000,
  //   originalPrice: 499000,
  //   rating: 4.8,
  //   reviewCount: "2,6RB",
  //   sold: "5RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/59.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Denim Short Pants Relaxed Fit hadir dengan desain santai dan nyaman dipakai. Terbuat dari bahan denim berkualitas, cocok untuk aktivitas santai dan gaya kasual harian.",
  //   shopeeLink: "https://s.shopee.co.id/dummy59",
  // tiktokLink: "",
  // },
  // {
  //   id: 60,
  //   code: "YYS-060",
  //   name: "JINISO - Jaket Jeans Street Casual",
  //   price: 225000,
  //   originalPrice: 620000,
  //   rating: 4.9,
  //   reviewCount: "7,9RB",
  //   sold: "14RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/60.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Jaket Jeans Street Casual hadir dengan desain modern yang cocok untuk gaya streetwear. Nyaman dipakai sebagai outer dan mudah dipadukan untuk berbagai aktivitas kasual.",
  //   shopeeLink: "https://s.shopee.co.id/dummy60",
  // tiktokLink: "",
  // },
  // {
  //   id: 61,
  //   code: "YYS-061",
  //   name: "JINISO - Loose Fit Jeans Everyday",
  //   price: 228000,
  //   originalPrice: 640000,
  //   rating: 4.9,
  //   reviewCount: "3,2RB",
  //   sold: "6RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/61.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Loose Fit Jeans Everyday hadir dengan potongan loose fit yang nyaman untuk dipakai sehari-hari. Dibuat dari denim berkualitas, celana ini cocok untuk tampilan kasual yang simpel dan modern.",
  //   shopeeLink: "https://s.shopee.co.id/dummy61",
  // tiktokLink: "",
  // },
  // {
  //   id: 62,
  //   code: "YYS-062",
  //   name: "JINISO - Straight Jeans Minimalist",
  //   price: 219000,
  //   originalPrice: 610000,
  //   rating: 4.8,
  //   reviewCount: "2,7RB",
  //   sold: "5RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/62.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Straight Jeans Minimalist hadir dengan desain simpel dan potongan lurus yang timeless. Cocok untuk berbagai aktivitas, mudah dipadukan dengan gaya kasual maupun semi-formal.",
  //   shopeeLink: "https://s.shopee.co.id/dummy62",
  // tiktokLink: "",
  // },
  // {
  //   id: 63,
  //   code: "YYS-063",
  //   name: "JINISO - Baggy Denim Pants Street Mode",
  //   price: 235000,
  //   originalPrice: 655000,
  //   rating: 4.9,
  //   reviewCount: "4,6RB",
  //   sold: "9RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/63.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Baggy Denim Pants Street Mode hadir dengan potongan baggy yang trendi dan nyaman. Terbuat dari denim berkualitas, cocok untuk gaya streetwear kekinian.",
  //   shopeeLink: "https://s.shopee.co.id/dummy63",
  // tiktokLink: "",
  // },
  // {
  //   id: 64,
  //   code: "YYS-064",
  //   name: "JINISO - Rok Jeans Midi Highwaist",
  //   price: 218000,
  //   originalPrice: 605000,
  //   rating: 4.8,
  //   reviewCount: "2,0RB",
  //   sold: "4RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/64.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Rok Jeans Midi Highwaist hadir dengan potongan highwaist yang elegan dan nyaman dipakai. Cocok untuk tampilan kasual maupun semi-formal dengan gaya modern.",
  //   shopeeLink: "https://s.shopee.co.id/dummy64",
  // tiktokLink: "",
  // },
  // {
  //   id: 65,
  //   code: "YYS-065",
  //   name: "JINISO - Denim Jacket Oversize Classic",
  //   price: 223000,
  //   originalPrice: 615000,
  //   rating: 4.9,
  //   reviewCount: "6,1RB",
  //   sold: "12RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/65.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Denim Jacket Oversize Classic hadir dengan desain jaket denim klasik berpotongan oversize. Nyaman dipakai sebagai outer dan cocok untuk berbagai gaya kasual.",
  //   shopeeLink: "https://s.shopee.co.id/dummy65",
  // tiktokLink: "",
  // },
  // {
  //   id: 66,
  //   code: "YYS-066",
  //   name: "JINISO - Tapered Jeans Casual Fit",
  //   price: 226000,
  //   originalPrice: 635000,
  //   rating: 4.8,
  //   reviewCount: "2,9RB",
  //   sold: "5RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/66.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Tapered Jeans Casual Fit hadir dengan potongan tapered yang nyaman dan modern. Terbuat dari denim berkualitas, cocok untuk aktivitas harian maupun hangout.",
  //   shopeeLink: "https://s.shopee.co.id/dummy66",
  // tiktokLink: "",
  // },
  // {
  //   id: 67,
  //   code: "YYS-067",
  //   name: "JINISO - Wide Jeans Oversize Daily",
  //   price: 232000,
  //   originalPrice: 650000,
  //   rating: 4.9,
  //   reviewCount: "4,3RB",
  //   sold: "8RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/67.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Wide Jeans Oversize Daily hadir dengan potongan wide yang nyaman dan stylish. Cocok untuk aktivitas harian dengan tampilan kasual modern.",
  //   shopeeLink: "https://s.shopee.co.id/dummy67",
  // tiktokLink: "",
  // },
  // {
  //   id: 68,
  //   code: "YYS-068",
  //   name: "JINISO - Denim Shorts Baggy Skater",
  //   price: 172000,
  //   originalPrice: 510000,
  //   rating: 4.8,
  //   reviewCount: "2,4RB",
  //   sold: "5RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/68.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Denim Shorts Baggy Skater hadir dengan potongan baggy yang santai dan nyaman. Cocok untuk gaya skater maupun kasual harian.",
  //   shopeeLink: "https://s.shopee.co.id/dummy68",
  // tiktokLink: "",
  // },
  // {
  //   id: 69,
  //   code: "YYS-069",
  //   name: "JINISO - Oversize Jeans Jacket Street",
  //   price: 227000,
  //   originalPrice: 625000,
  //   rating: 4.9,
  //   reviewCount: "5,7RB",
  //   sold: "11RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/69.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Oversize Jeans Jacket Street hadir dengan desain jaket denim oversize yang stylish dan kekinian. Cocok sebagai outer untuk gaya streetwear modern.",
  //   shopeeLink: "https://s.shopee.co.id/dummy69",
  // tiktokLink: "",
  // },
  // {
  //   id: 70,
  //   code: "YYS-070",
  //   name: "JINISO - Loose Fit Jeans Minimalist",
  //   price: 234000,
  //   originalPrice: 660000,
  //   rating: 4.9,
  //   reviewCount: "3,9RB",
  //   sold: "7RB+",
  //   location: "KOTA JAKARTA UTARA",
  //   image: "storage/70.webp",
  //   category: "Fashion",
  //   description:
  //     "JINISO – Loose Fit Jeans Minimalist hadir dengan potongan loose fit yang simpel dan nyaman dipakai. Terbuat dari denim berkualitas tinggi, jeans ini cocok untuk berbagai aktivitas dengan tampilan kasual modern.",
  //   shopeeLink: "https://s.shopee.co.id/dummy70",
  // tiktokLink: "",
  // },
];
