const products = [
  {
    id: 1,
    code: "YYS-001",
    name: "Benidson Aerysm Kaos Oversized T-Shirt Polos Korean Style",
    price: 79900,
    originalPrice: 200000,
    rating: 4.9,
    reviewCount: 202,
    sold: 863,
    location: "KAB. BANYUWANGI",
    image: "storage/1.webp",
    category: "Fashion",
    description:
      "Benidson Aerysm Kaos Oversized T-Shirt Polos Korean Style hadir dengan bahan Aerysm yang ringan, adem, dan super nyaman dipakai seharian, memberikan sensasi lembut di kulit serta sirkulasi udara yang baik. Desain polos minimalis dengan potongan oversized ala Korean style membuat tampilan terlihat clean, modern, dan effortlessly stylish, mudah dipadukan dengan berbagai outfit seperti jeans, cargo, atau outer favorit untuk aktivitas harian, hangout, maupun casual look.",
    shopeeLink: "https://s.shopee.co.id/8fLf47UXRo",
  },
  {
    id: 2,
    code: "YYS-002",
    name: "Benidson Oversized Tshirt Kaos Garis-Garis Katun",
    price: 108400,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "2,3RB",
    sold: "5RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/2.webp",
    category: "Fashion",
    description:
      "Tampil santai dan stylish dengan Benidson Oversized Tshirt berbahan katun premium yang lembut, adem, dan nyaman dipakai seharian. Desain garis-garis modern memberikan kesan kasual kekinian, cocok untuk berbagai aktivitas seperti hangout, kuliah, kerja santai, hingga daily outfit.",
    shopeeLink: "https://s.shopee.co.id/gJNbCEfYt",
  },
  {
    id: 3,
    code: "YYS-003",
    name: "Benidson Oversized Tshirt Liquor Katun Korean",
    price: 99900,
    originalPrice: 200000,
    rating: 4.9,
    reviewCount: 801,
    sold: "2RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/3.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Tshirt Liquor Katun Korean hadir dengan desain grafis bertema liquor yang bold dan stylish, dipadukan dengan bahan katun berkualitas yang lembut, adem, dan nyaman dipakai seharian. Potongan oversized ala Korean style memberikan kesan trendy dan santai, cocok untuk daily outfit, hangout, atau streetwear look, serta mudah dipadukan dengan jeans, cargo, maupun sneakers favorit.",
    shopeeLink: "https://s.shopee.co.id/VzxPCkC9x",
  },
  {
    id: 4,
    code: "YYS-004",
    name: "BENIDSON Oversized Tshirt Sheesh",
    price: 99900,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "3,5RB",
    sold: "7RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/4.webp",
    category: "Fashion",
    description:
      "BENIDSON Oversized Tshirt Sheesh hadir dengan desain grafis “Sheesh” yang catchy dan penuh karakter, cocok untuk kamu yang ingin tampil standout dengan gaya kasual modern. Dibuat dari bahan katun yang adem, lembut, dan nyaman dipakai seharian, kaos ini mengusung potongan oversized yang mengikuti tren Korean street style, mudah dipadukan dengan berbagai outfit untuk aktivitas harian maupun hangout.",
    shopeeLink: "https://s.shopee.co.id/8V2EwAnyRp",
  },
  {
    id: 5,
    code: "YYS-005",
    name: "Benidson Oversized Kaos Bump Katun Korean Style",
    price: 99900,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "2,6RB",
    sold: "5RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/5.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Kaos Bump Katun Korean Style hadir dengan desain grafis “Bump” yang simpel namun eye-catching, dipadukan dengan bahan katun berkualitas yang lembut, adem, dan nyaman dipakai sepanjang hari. Potongan oversized khas Korean style memberikan tampilan kasual modern yang trendy, mudah dipadukan dengan jeans, cargo, atau outfit favorit untuk daily look dan hangout.",
    shopeeLink: "https://s.shopee.co.id/3B0iaajRTw",
  },
  {
    id: 6,
    code: "YYS-006",
    name: "Benidson Oversized Tshirt Stick Logo Katun M-2XL",
    price: 99900,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "2,8RB",
    sold: "5RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/6.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Tshirt Stick Logo Katun M–2XL hadir dengan desain logo stick yang minimalis dan modern, cocok untuk tampilan simpel namun tetap stylish. Terbuat dari bahan katun berkualitas yang adem, lembut, dan nyaman dipakai seharian, kaos ini menggunakan potongan oversized ala Korean style dengan pilihan ukuran M hingga 2XL, mudah dipadukan dengan berbagai outfit untuk aktivitas harian maupun hangout.",
    shopeeLink: "https://s.shopee.co.id/2LRbbIQfvV",
  },
  {
    id: 7,
    code: "YYS-007",
    name: "Benidson Oversized Tshirt Katun Unisex L-2XL",
    price: 99900,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "5,2RB",
    sold: "10RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/7.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Tshirt Katun Unisex L–2XL hadir dengan desain simpel dan potongan oversized yang nyaman, cocok digunakan oleh pria maupun wanita. Terbuat dari bahan katun berkualitas yang adem, lembut, dan menyerap keringat, kaos ini nyaman dipakai seharian serta mudah dipadukan dengan berbagai gaya outfit kasual untuk aktivitas harian, hangout, maupun santai.",
    shopeeLink: "https://s.shopee.co.id/9zr2jUYf8y",
  },
  {
    id: 8,
    code: "YYS-008",
    name: "Benidson Oversized Tshirt Squarepants Power Katun M-2XL",
    price: 99900,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "2,4RB",
    sold: "4RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/8.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Tshirt Squarepants Power Katun M–2XL hadir dengan desain grafis Squarepants Power yang fun dan eye-catching, cocok untuk kamu yang ingin tampil playful namun tetap stylish. Terbuat dari bahan katun berkualitas yang adem, lembut, dan nyaman dipakai seharian, kaos ini mengusung potongan oversized ala Korean style dengan pilihan ukuran M hingga 2XL, mudah dipadukan dengan berbagai outfit kasual untuk daily look maupun hangout.",
    shopeeLink: "https://s.shopee.co.id/2LRbbfOwkG",
  },
  {
    id: 9,
    code: "YYS-009",
    name: "Benidson Oversized Tshirt Green Issue Katun Korean",
    price: 99900,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: "1,1RB",
    sold: "2RB+",
    location: "KAB. BANYUWANGI",
    image: "storage/9.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Tshirt Green Issue Katun Korean hadir dengan desain bertema Green Issue yang modern dan berkarakter, cocok untuk tampilan kasual yang fresh dan kekinian. Terbuat dari bahan katun berkualitas yang adem, lembut, dan nyaman dipakai seharian, kaos ini mengusung potongan oversized ala Korean style sehingga mudah dipadukan dengan berbagai outfit untuk aktivitas harian maupun hangout.",
    shopeeLink: "https://s.shopee.co.id/8zyVY6ydcr",
  },
  {
    id: 10,
    code: "YYS-010",
    name: "Benidson Oversized Tshirt Jaguars Katun Korean",
    price: 99900,
    originalPrice: 200000,
    rating: 4.9,
    reviewCount: "149",
    sold: "440",
    location: "KAB. BANYUWANGI",
    image: "storage/10.webp",
    category: "Fashion",
    description:
      "Benidson Oversized Tshirt Jaguars Katun Korean hadir dengan desain grafis Jaguars yang bold dan sporty, memberikan kesan kuat dan stylish pada tampilan kasualmu. Dibuat dari bahan katun berkualitas yang adem, lembut, dan nyaman dipakai seharian, kaos ini mengusung potongan oversized ala Korean style yang trendy dan mudah dipadukan dengan berbagai outfit untuk aktivitas harian maupun hangout.",
    shopeeLink: "https://s.shopee.co.id/1gBuop112T",
  },
];
